# Site settings
title: Music Intelligence Lab
email: jb50@aub.edu.lb
description: >-
  Music, technology, and intelligence at the American University of Beirut.
  New instruments, machine learning for music, and computational musicology of
  the Arab region.
baseurl: ""
url: "https://musicintelligencelab.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
